/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "I2S.h"



I2S_Config INMP441_I2S;

int main(void)
{
	MCU_Clock_Setup();
	Delay_Config();
	Console_Init(USART1, 9600);


	I2S_DeInit(&INMP441_I2S);


	INMP441_I2S.Port = I2S_Port.I2S2;
	INMP441_I2S.Audio_Frequency = I2S_Audio_Frequency._48000Hz;
	INMP441_I2S.Channel_Length = I2S_Channel_Length._16_bit;
	INMP441_I2S.Data_Length = I2S_Data_Length._16_bit;
	INMP441_I2S.LR_Pin_Port = GPIOB;
	INMP441_I2S.LR_Pin_Number = 12;
	INMP441_I2S.Standard = I2S_Standard.Standard_Philips;
	INMP441_I2S.Half_Duplex.Enable = true;
	INMP441_I2S.Half_Duplex.mode = I2S_Mode.Master.Receive;
	INMP441_I2S.Half_Duplex.WS_Pin = I2S_Pin.WS.I2S2.PB09;
	INMP441_I2S.Half_Duplex.SD_Pin = I2S_Pin.SD.I2S2.PB15;
	INMP441_I2S.Half_Duplex.SCK_Pin = I2S_Pin.SCK.I2S2.PB13;

	if(I2S_Init(&INMP441_I2S)) I2S_Print_Errors(&INMP441_I2S);



	I2S_Select_Left_Channel(&INMP441_I2S);
	uint32_t x = 0;


	for(;;)
	{
		x = I2S_Read_Data(&INMP441_I2S);
		printConsole("%"PRId32"\r\n",x);
	}
}
